services:
  esi-php:
    image: silarhi/php-apache:8.3
    volumes:
      - ./php:/app:ro
    ports:
      - '8081:80'

  varnish:
    image: varnish:7.3-alpine
    command: [ "varnishd", "-F", "-f", "/etc/varnish/default.vcl", "-t", "0" ]
    depends_on:
      - esi-php
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl:ro
    ports:
      - '8080:80'
